// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using quizzAPI.Data;

#nullable disable

namespace quizzAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201003456_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("quizzAPI.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAcesso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CriadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroMembros")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroQuizzes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("quizzAPI.Models.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativaA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlternativaB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlternativaC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlternativaD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dificuldade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Justificativa")
                        .HasColumnType("text");

                    b.Property<string>("NivelEscolar")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PerguntaTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizzId")
                        .HasColumnType("integer");

                    b.Property<string>("RespostaCorreta")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Tema")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("QuizzId");

                    b.ToTable("Perguntas", (string)null);
                });

            modelBuilder.Entity("quizzAPI.Models.Quizz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CriadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.PrimitiveCollection<List<string>>("Dificuldade")
                        .HasColumnType("text[]");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<string>("NivelEscolar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NumeroPerguntas")
                        .HasColumnType("integer");

                    b.Property<string>("Objetivo")
                        .HasColumnType("text");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Temas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.HasIndex("GrupoId");

                    b.ToTable("Quizz", (string)null);
                });

            modelBuilder.Entity("quizzAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("quizzAPI.Models.UsuarioGrupo", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("UsuariosGrupos");
                });

            modelBuilder.Entity("quizzAPI.Models.Grupo", b =>
                {
                    b.HasOne("quizzAPI.Models.User", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("quizzAPI.Models.Pergunta", b =>
                {
                    b.HasOne("quizzAPI.Models.Quizz", "Quizz")
                        .WithMany("Perguntas")
                        .HasForeignKey("QuizzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quizz");
                });

            modelBuilder.Entity("quizzAPI.Models.Quizz", b =>
                {
                    b.HasOne("quizzAPI.Models.User", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId");

                    b.HasOne("quizzAPI.Models.Grupo", "Grupo")
                        .WithMany("Quizzes")
                        .HasForeignKey("GrupoId");

                    b.Navigation("Criador");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("quizzAPI.Models.UsuarioGrupo", b =>
                {
                    b.HasOne("quizzAPI.Models.Grupo", "Grupo")
                        .WithMany("Membros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quizzAPI.Models.User", "User")
                        .WithMany("Grupos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("quizzAPI.Models.Grupo", b =>
                {
                    b.Navigation("Membros");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("quizzAPI.Models.Quizz", b =>
                {
                    b.Navigation("Perguntas");
                });

            modelBuilder.Entity("quizzAPI.Models.User", b =>
                {
                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
